"""init-profiles

Revision ID: b17a553d26c2
Create Date: 2025-02-14 18:19:45.757643
"""

from alembic import op

import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b17a553d26c2"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profiles_profile",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("public", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        mysql_collate="utf8mb4_bin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profiles_profile")
    # ### end Alembic commands ###
